### ISSUE TITLE
Cluster config not persistent

### ISSUE THREAD

**Issue by lexasoft123** [eshepelyuk/cmak-operator#2]
Hello!
Due to zookeeper has no storage, and cluster config is applied only once on creation via job, cluster list is not persistent and will disappear after every CMAK pod recreation.
There is 2 possible ways to solve this:
1) Add persistent storage to Zookeeper.
2) Run cluster population script in an initContainer.
Thanks.

**Comment by eshepelyuk** [comment]
Thnx for opening a bug. I am still thinking about proper fix for the issue.

**Comment by sharkymcdongles** [comment]
Ya this is a pretty big bug as it just makes the tool unusable. Perhaps adding an option to the chart to either add a disk or init is a flexible solution.

**Comment by eshepelyuk** [comment]
PRs are welcomed, btw.

**Comment by sharkymcdongles** [comment]
I am making one don't worry, I just was giving you the two approaches I may
take. I just made changes in my flux repo. If it works as expected I will
add as a PR.

Would you also be receptive to having a toggleable ingress?

**Comment by eshepelyuk** [comment]
> Would you also be receptive to having a toggleable ingress?

Absolutely, I'd just prefer to have it in the different PR

**Comment by sharkymcdongles** [comment]
I will test it over the next day or two. If it keeps working I will submit my changes as a PR. I will also submit a separate one for the ingress then as well.

To get the initcontainer approach to work I had to split the zk and cmak deployments into two with separate services because the cmak job needs zk running or it won't execute. The job runs as an initcontainer to cmak-ui and watches for zk service to be active then runs and it all boots.

**Comment by eshepelyuk** [comment]
Do you still need k8s Job while using initContainer for putting config into ZK ?
I suppose, don't.

initContainer should be added to ZK, not to cmak-ui.
Since the data disappeares when ZK container restarts.

Well, if you think about recinciliation, then it is not an initContainer approach, but a separate deployment should be created that reconciles ConfigMap to ZK if the data disappers.

**Comment by eshepelyuk** [comment]
Maybe I just misunderstood the approach, i am open for further design discussion.

**Comment by sharkymcdongles** [comment]
Okay so you were 100% correct putting it as an init container for the UI wouldn't work longterm. I instead went for an approach where the zookeeper pod has an init container that creates the setup job from a mounted configmap. This way on each reboot the job will run until the zookeeper is up. So far it seems to work. If it has no issues I will try and have a PR this week.

**Comment by eshepelyuk** [comment]
Good news @sharkymcdongles , thanks

**Comment by lexasoft123** [comment]
@sharkymcdongles any news on this?

**Comment by sharkymcdongles** [comment]
Sorry I took the week off for Thanksgiving. It seems to work though as I
heard no complaints after making the change. I will submit a PR for the job
tweak first then the ingress separate. I hope to do it Monday or Tuesday.

**Comment by eshepelyuk** [comment]
Please take a look at PR #3

**Comment by eshepelyuk** [comment]
@sharkymcdongles @lexasoft123 released 0.7.0

Please give it a try.
