### ISSUE TITLE
Consumer data missing for all cluster when Error for one cluster

### ISSUE THREAD

**Issue by jeffery** [eshepelyuk/cmak-operator#59]
Hi there,

I am trying to troubleshoot an issue where the Consumer data is missing when we add one particular cluster to the pool.

In the UI container logs I see

> [ERROR] k.m.a.c.KafkaAdminClientActor - AdminClient not initialized yet, cannot process request : KAGetGroupSummary(ArrayBuffer(<consumer-group-name>),[])

Once we remove this particular cluster from the pool of clusters, all data related to consumer for all clusters are visible. 

Any help with debugging this issue is appreciated. 

Version used: 2.2.0

**Comment by eshepelyuk** [comment]
Hello @jeffery 

Unfortunately I dont think I can help you with that.
This helm chart just insalls CMAK and makes sure that declarative cluster configuration is synchronized to CMAK instance.

The cluster configuration and connection issues may be caused by CMAK setting or your cluster internal settings.

I suggest you to ask this question in CMAK repo,unless you can show me that helm chart somehow affects cmak pod behaviour.

**Comment by jeffery** [comment]
Thanks @eshepelyuk , I will verify if this is a bug with CMAK project.
